ALTER USER 'root'@'%' IDENTIFIED BY 'root' PASSWORD EXPIRE NEVER;

ALTER USER 'root'@'%' IDENTIFIED WITH MYSQL_NATIVE_PASSWORD BY 'root';

FLUSH PRIVILEGES;

CREATE TABLE USER (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL ,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	user_name VARCHAR(50),
	email VARCHAR(50),
	access_level INT,
	access_card INT
);

INSERT INTO USER (first_name, last_name, user_name, email, access_level, access_card) VALUES
('Corilla',   'Rosendahl',    'crosendahl0',     'crosendahl0@apache.org',           2, 399155),
('Alys',      'Garvey',       'agarvey1',        'agarvey1@paginegialle.it',         4, 906785),
('Ambrose',   'Whilde',       'awhilde2',        'awhilde2@mtv.com',                 4, 129925),
('Karl',      'Janoschek',    'kjanoschek3',     'kjanoschek3@mayoclinic.com',       3, 410474),
('Ardene',    'Harbar',       'aharbar4',        'aharbar4@theguardian.com',         5, 781728),
('Tisha',     'Struis',       'tstruis5',        'tstruis5@surveymonkey.com',        1, 855596),
('Latrena',   'Nowak',        'lnowak6',         'lnowak6@dion.ne.jp',               4, 614774),
('Gian',      'Polleye',      'gpolleye7',       'gpolleye7@ihg.com', 	             5, 951376),
('Gib',       'Greasty',      'ggreasty8',       'ggreasty8@gnu.org', 	             2, 936720),
('Carolan',   'Tappin',       'ctappin9',        'ctappin9@digg.com', 	             2, 229117),
('Konrad',    'Dougharty',    'kdoughartya',     'kdoughartya@prnewswire.com',       2, 980538),
('Sadie', 	  'Carmody',      'socarmodyb',      'socarmodyb@dell.com',              3, 137022),
('Anna',      'Bradnock',     'abradnockc',      'abradnockc@imdb.com',              4, 904214),
('Anastasie', 'Kinghorn',     'akinghornd',      'akinghornd@hhs.gov',               3, 832438),
('Marlene',   'Jakubovits',   'mjakubovitse',    'mjakubovitse@shareasale.com',      5, 618210),
('Leigh',     'Pickering',    'lpickeringf',     'lpickeringf@sfgate.com',           3, 410895),
('Matty',     'Full',         'mfullg',          'mfullg@opera.com',                 2, 892982),
('Clari',     'MacSween',     'cmacsweenh',      'cmacsweenh@multiply.com',          2, 342090),
('Terrye',    'Weiser',       'tweiseri',        'tweiseri@businesswire.com',        1, 433892),
('Meredith',  'Gaynsford',    'mgaynsfordj',     'mgaynsfordj@dailymail.co.uk',      3, 156524),
('Glory',     'Duffrie',      'gduffriek',       'gduffriek@businesswire.com',       5, 256501),
('Anna',      'Village',      'avillagel',       'avillagel@bing.com',               4, 867960),
('Yul',       'Merriton',     'ymerritonm',      'ymerritonm@mapquest.com',          3, 113242),
('Charline',  'Bedminster',   'cbedminstern',    'cbedminstern@ucla.edu',            4, 494057),
('Leyla',     'Fulstow',      'lfulstowo',       'lfulstowo@topsy.com',              3, 282875),
('Vanya',     'Beaven',       'vbeavenp',        'vbeavenp@dagondesign.com',         3, 770812),
('Florinda',  'Aymer',        'faymerq',         'faymerq@usda.gov',                 3, 359121),
('Aurlie',    'Chaplin',      'achaplinr',       'achaplinr@yelp.com',               2, 402326),
('Marybeth',  'Book',         'mbooks',          'mbooks@blinklist.com',             1, 682355),
('Matt',      'Skipper',      'mskippert',       'mskippert@multiply.com',           1, 312392),
('Berna',     'Cowlas',       'bcowlasu',        'bcowlasu@state.tx.us',             2, 246422),
('Loralee',   'Tunny',        'ltunnyv',         'ltunnyv@sfgate.com',               4, 991424),
('Carlin',    'Roads',        'croadsw',         'croadsw@wikimedia.org',            3, 795076),
('Brenda',    'Cammell',      'bcammellx',       'bcammellx@163.com',                1, 426995),
('Perry',     'Durtnal',      'pdurtnaly',       'pdurtnaly@nationalgeographic.com', 2, 441970),
('Ervin',     'Marquet',      'emarquetz',       'emarquetz@earthlink.net',          2, 182062),
('Madison',   'Gilvear',      'mgilvear10',      'mgilvear10@squarespace.com',       3, 211727),
('Fredra',    'Stanman',      'fstanman11',      'fstanman11@creativecommons.org',   5, 488061),
('Roscoe',    'Grellis',      'rgrellis12',      'rgrellis12@seattletimes.com',      2, 611566),
('Isidora',   'Sancias',      'isancias13',      'isancias13@statcounter.com',       4, 231436),
('Lynn',      'Demare',       'ldemare14',       'ldemare14@topsy.com',              4, 678783),
('Brent',     'Bromwich',     'bbromwich15',     'bbromwich15@bravesites.com',       2, 471566),
('June',      'Petti',        'jpetti16',        'jpetti16@ebay.co.uk',              4, 411821),
('Cybil',     'Drews',        'cdrews17',        'cdrews17@pcworld.com',             2, 752640),
('Arvie',     'Seine',        'aseine18',        'aseine18@soundcloud.com',          5, 322531),
('Phyllis',   'Mildmott',     'pmildmott19',     'pmildmott19@epa.gov',              5, 715656),
('Herminia',  'Duprey',       'hduprey1a',       'hduprey1a@answers.com',            5, 545157),
('Zed',       'Held',         'zheld1b',         'zheld1b@usa.gov',                  5, 825807),
('Cole',      'Riggeard',     'criggeard1c',     'criggeard1c@unicef.org',           1, 960025),
('Claribel',  'Udey',         'cudey1d',         'cudey1d@theguardian.com',          4, 267684),
('Reuben',    'Traher',       'rtraher1e',       'rtraher1e@desdev.cn',              5, 235852),
('Griff',     'Bollom',       'gbollom1f',       'gbollom1f@amazon.co.uk',           2, 873317),
('Edgar',     'Knill',        'eknill1g',        'eknill1g@bbb.org',                 2, 441015),
('Bowie',     'Rennicks',     'brennicks1h',     'brennicks1h@livejournal.com',      4, 943755),
('Hurlee',    'Lafay',        'hlafay1i',        'hlafay1i@marriott.com',            1, 791231),
('Eirena',    'Soigoux',      'esoigoux1j',      'esoigoux1j@sfgate.com',            1, 115806),
('Holli',     'Arnault',      'harnault1k',      'harnault1k@ocn.ne.jp',             5, 291211),
('Kristian',  'Desporte',     'kdesporte1l',     'kdesporte1l@vistaprint.com',       3, 733947),
('Vin',       'Francke',      'vfrancke1m',      'vfrancke1m@gnu.org',               1, 570404),
('Daniel',    'Mathers',      'dmathers1n',      'dmathers1n@multiply.com',          2, 437159),
('Falito',    'Mullaney',     'fmullaney1o',     'fmullaney1o@zdnet.com',            5, 596026),
('Sheryl',    'Give', 		  'sgive1p',         'sgive1p@mozilla.org',              4, 168726),
('Fredra',    'Graeser',      'fgraeser1q',      'fgraeser1q@scribd.com',            2, 359807),
('Henrik',    'Pickett',      'hpickett1r',      'hpickett1r@pinterest.com',         5, 389632),
('Der',       'Hawkridge',    'dhawkridge1s',    'dhawkridge1s@earthlink.net',       1, 295874),
('Addy',      'Sineath',      'asineath1t',      'asineath1t@theguardian.com',       3, 362366),
('Jannelle',  'Greenin',      'jgreenin1u',      'jgreenin1u@about.me',              5, 304568),
('Galen',     'Tregale',      'gtregale1v',      'gtregale1v@cloudflare.com',        3, 727084),
('Antonino',  'Godon',        'agodon1w',        'agodon1w@photobucket.com',         5, 578821),
('Gilburt',   'Pieterick',    'gpieterick1x',    'gpieterick1x@gnu.org',             5, 766648),
('Tracey',    'Keirl',        'tkeirl1y',        'tkeirl1y@theatlantic.com',         2, 133743),
('Leopold',   'Langdridge',   'llangdridge1z',   'llangdridge1z@ning.com',           1, 884046),
('Rossy',     'Grancher',     'rgrancher20',     'rgrancher20@google.fr',            5, 281300),
('Pepe',      'Huke',         'phuke21',         'phuke21@buzzfeed.com',             3, 864561),
('Andee',     'Nuth',         'anuth22',         'anuth22@desdev.cn',                2, 944426),
('Correy',    'Quartermaine', 'cquartermaine23', 'cquartermaine23@fda.gov',          4, 714470),
('Willette',  'La Torre',     'wlatorre24',      'wlatorre24@wiley.com',             2, 289618),
('Annabela',  'Wildber',      'awildber25',      'awildber25@tuttocitta.it',         2, 113713),
('Cordy',     'Naptin',       'cnaptin26',       'cnaptin26@weather.com',            2, 536840),
('Delbert',   'Keward',       'dkeward27',       'dkeward27@fc2.com',                1, 157911),
('Mitchel',   'Bower',        'mbower28',        'mbower28@ow.ly',                   2, 688684),
('Evania',    'Haymes', 	  'ehaymes29',       'ehaymes29@gravatar.com',           3, 540893),
('Lek',       'Tolemache',    'ltolemache2a',    'ltolemache2a@sitemeter.com',       1, 356599),
('Fawnia',    'De Domenico',  'fdedomenico2b',   'fdedomenico2b@ca.gov',             1, 710104),
('Marietta',  'Dunsmuir',     'mdunsmuir2c',     'mdunsmuir2c@geocities.com',        2, 543139),
('Jelene',    'Terbeek',      'jterbeek2d',      'jterbeek2d@merriam-webster.com',   5, 514911),
('Anatollo',  'Crosthwaite',  'acrosthwaite2e',  'acrosthwaite2e@is.gd',             5, 386353),
('Darrel',    'Booler',       'dbooler2f',       'dbooler2f@huffingtonpost.com',     4, 781845),
('Timothy',   'Kynder',       'tkynder2g',       'tkynder2g@bloomberg.com',          4, 202290),
('Miguela',   'Copper',       'mcopper2h',       'mcopper2h@apache.org',             4, 232912),
('Teresita',  'Thorwarth',    'tthorwarth2i',    'tthorwarth2i@cbc.ca',              2, 406176),
('Correy',    'Shanks',       'cshanks2j', 	     'cshanks2j@shinystat.com',          3, 623484),
('Jesse',     'Dymott',       'jdymott2k',       'jdymott2k@nationalgeographic.com', 2, 441066),
('Jessey',    'Harnott',      'jharnott2l',      'jharnott2l@uiuc.edu',              4, 780385),
('Adda',      'McCoid',       'amccoid2m',       'amccoid2m@opera.com',              5, 129533),
('Terza',     'Hullett',      'thullett2n',      'thullett2n@163.com',               2, 936531),
('Christye',  'Ablewhite',    'cablewhite2o',    'cablewhite2o@nyu.edu',             2, 592623),
('Tabatha',   'Iacavone',     'tiacavone2p',     'tiacavone2p@google.com.hk',        3, 418691),
('Lynea',     'Agdahl',       'lagdahl2q',       'lagdahl2q@chicagotribune.com',     1, 785384),
('Cletus',    'Espinas',      'cespinas2r',      'cespinas2r@opensource.org',        1, 696795);