###
GET http://localhost:3000/api HTTP/1.1

###
GET http://localhost:3000/api/1 HTTP/1.1



###
POST http://localhost:3000/api HTTP/1.1
Content-Type: application/json

{
    "first_name": "Jota",
    "last_name": "Be",
    "user_name": "jotabe",
    "email": "jotabe@example.com",
    "access_level": 1,
    "access_card": 444555
}

###
PUT http://localhost:3000/api/101 HTTP/1.1
Content-Type: application/json

{
    "access_level": 5
}

###
DELETE http://localhost:3000/api/101 HTTP/1.1